<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'id' => 13,
                'organizer_id' => 5,
                'title' => 'Coba event baru',
                'description' => 'ajdksajdka',
                'starts_at' => '2026-06-10 13:00:00',
                'location' => 'Cobaaa',
                'type' => 'workshop',
                'image_emoji' => '💻',
                'status' => 1,
                'attendees_count' => 0,
                'ends_at' => '2026-06-10 15:00:00',
            ],
            [
                'id' => 8,
                'organizer_id' => 11,
                'title' => 'Event AI updated list',
                'description' => 'Coba lagi upadted',
                'starts_at' => '2026-06-09 19:30:00',
                'location' => 'Grand Indonesia',
                'type' => 'workshop',
                'image_emoji' => '🎤',
                'status' => 1,
                'attendees_count' => 1,
                'ends_at' => '2026-06-09 23:30:00',
            ],
            [
                'id' => 12,
                'organizer_id' => 11,
                'title' => 'event mundur',
                'description' => 'skdakdkad',
                'starts_at' => '2026-06-04 20:00:00',
                'location' => 'cobaa',
                'type' => 'networking',
                'image_emoji' => '🍽️',
                'banner_media_id' => null,
                'status' => 2,
                'attendees_count' => 0,
                'ends_at' => '2026-06-04 20:30:00',
                'created_at' => '2026-06-10 00:53:59',
                'updated_at' => '2026-06-10 00:53:59',
            ],
            [
                'id' => 10,
                'organizer_id' => 11,
                'title' => 'Coba event baru',
                'description' => 'coba event',
                'starts_at' => '2026-06-12 03:44:00',
                'location' => 'Virtual event',
                'type' => 'conference',
                'image_emoji' => '🎯',
                'banner_media_id' => null,
                'status' => 1,
                'attendees_count' => 1,
                'ends_at' => '2026-06-12 04:44:00',
                'created_at' => '2026-06-10 00:44:37',
                'updated_at' => '2026-06-10 01:00:27',
            ],
            [
                'id' => 11,
                'organizer_id' => 11,
                'title' => 'coba webinar',
                'description' => 'coba webinar',
                'starts_at' => '2026-06-30 20:00:00',
                'location' => 'Kota kasablanka',
                'type' => 'webinar',
                'image_emoji' => '🎤',
                'banner_media_id' => null,
                'status' => 1,
                'attendees_count' => 0,
                'ends_at' => '2026-06-30 21:45:00',
                'created_at' => '2026-06-10 00:46:59',
                'updated_at' => '2026-06-18 00:49:46',
            ],
            [
                'id' => 7,
                'organizer_id' => 5,
                'title' => 'Coba event baru update',
                'description' => 'ini coba deskripsi',
                'starts_at' => '2026-06-08 12:00:00',
                'location' => 'Coba Kota kasablanka',
                'type' => 'workshop',
                'image_emoji' => '🎯',
                'banner_media_id' => null,
                'status' => 2,
                'attendees_count' => 2,
                'ends_at' => '2026-06-08 21:00:00',
                'created_at' => '2026-06-08 18:18:52',
                'updated_at' => '2026-06-10 01:00:51',
            ],
            [
                'id' => 4,
                'organizer_id' => 5,
                'title' => 'Coba event baru upadte',
                'description' => 'coba kasablanka',
                'starts_at' => '2026-06-09 02:09:00',
                'location' => 'Kota kasablanka',
                'type' => 'conference',
                'image_emoji' => '🎯',
                'banner_media_id' => null,
                'status' => 1,
                'attendees_count' => 0,
                'ends_at' => '2026-06-09 04:09:00',
                'created_at' => '2026-06-08 17:45:40',
                'updated_at' => '2026-06-08 18:11:13',
            ],
            [
                'id' => 5,
                'organizer_id' => 5,
                'title' => 'Coba event baru update',
                'description' => 'Cobaa deskripsi',
                'starts_at' => '2027-02-12 09:00:00',
                'location' => 'Coba kota kasablanka',
                'type' => 'conference',
                'image_emoji' => '🎯',
                'banner_media_id' => null,
                'status' => 1,
                'attendees_count' => 5,
                'ends_at' => '2027-02-12 11:00:00',
                'created_at' => '2026-06-08 17:47:06',
                'updated_at' => '2026-06-08 18:11:13',
            ],
            [
                'id' => 6,
                'organizer_id' => 5,
                'title' => 'Coba lagi',
                'description' => 'sandaj',
                'starts_at' => '2026-06-09 02:00:00',
                'location' => 'Nama location',
                'type' => 'webinar',
                'image_emoji' => '🎤',
                'banner_media_id' => null,
                'status' => 1,
                'attendees_count' => 0,
                'ends_at' => '2026-06-09 04:00:00',
                'created_at' => '2026-06-08 18:01:33',
                'updated_at' => '2026-06-08 18:11:13',
            ],
            [
                'id' => 9,
                'organizer_id' => 11,
                'title' => 'coba event ai',
                'description' => 'okee',
                'starts_at' => '2026-06-08 18:30:00',
                'location' => 'kokas',
                'type' => 'networking',
                'image_emoji' => '🍽️',
                'banner_media_id' => null,
                'status' => 1,
                'attendees_count' => 0,
                'ends_at' => '2026-06-08 20:26:00',
                'created_at' => '2026-06-08 18:26:47',
                'updated_at' => '2026-06-10 01:01:16',
            ],
            [
                'id' => 14,
                'organizer_id' => 23,
                'title' => 'Cobaa event buat score',
                'description' => 'coba aja',
                'starts_at' => '2026-07-13 20:00:00',
                'location' => 'Virtual',
                'type' => 'workshop',
                'image_emoji' => '💻',
                'banner_media_id' => null,
                'status' => 1,
                'attendees_count' => 1,
                'ends_at' => '2026-07-13 21:00:00',
                'created_at' => '2026-07-13 11:38:20',
                'updated_at' => '2026-07-13 11:40:28',
            ]
        ];

        foreach ($events as $event) {
            \App\Models\Event::create($event);
        }
    }
}
